### ISSUE TITLE
Can't convert 'list' object to str implicitly

### ISSUE THREAD

**Issue by ashee** [ternjs/tern_for_vim#138]
# Environment
## vim
```
NVIM v0.1.5-92-g490804e
Build type: Release
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160503-66322-qzx2y5/build/config -I/tmp/neovim-20160503-66322-qzx2y5/src -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160503-66322-qzx2y5/build/src/nvim/auto -I/tmp/neovim-20160503-66322-qzx2y5/build/include
Compiled by amitava@amitava.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

## OS 
```
OSX Yosemite
Version 10.10.5 

$ uname -a
Darwin amitava.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
```

# VIM error
```
Error detected while processing function provider#python3#Call:
line   18:
TypeError("Can't convert 'list' object to str implicitly",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
    result = request_cb(self._from_nvim(name), args)
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 74, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 160, in decoder
    return fn(*walk(decode_if_bytes, args, decode))
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/script_host.py", line 75, in python_execute
    exec(script, self.module.__dict__)
TypeError: Can't convert 'list' object to str implicitly
```

**Comment by marijnh** [comment]
None of the calls in that backtrace appear to be related to tern_for_vim. Are you sure this is related to this repository?

**Comment by ashee** [comment]
Oops - forgot to mention that this error is triggered when I invoke any of the :TernXX commands - e.g. 

:TernDef
