### ISSUE TITLE
Symbol not found: __PyCodecInfo_GetIncrementalDecoder

### ISSUE THREAD

**Issue by lonelyelk** [ternjs/tern_for_vim#161]
Installed `ternjs/tern_for_vim` with `vim-plug`

When opening javascript files, get the following error:

```
Error detected while processing /path/to/tern_for_vim/autoload/tern.vim:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/tern_for_vim/script/tern.py", line 5, in <module>
    import urllib2 as request
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
Press ENTER or type command to continue
```

Setup:

- Mac OS Sierra Version 10.12.3 (16D32)
- VIM - Vi IMproved 7.4
- Python 2.7.13

None of the [solutions proposed on SO](http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder) worked for me.

**Comment by marijnh** [comment]
That's a python issue though, not something related to tern_for_vim

**Comment by lonelyelk** [comment]
@marijnh do you happen to know where to file this report though? Or any other more isolated way to demonstrate it? Since you are sure it is python's problem. I've never had any experience with python.

**Comment by marijnh** [comment]
It's an issue with Python not being able to find its own shared library, if I understand the descriptions I found online correctly. This may be related to the way Vim loads python, or your system's python. Not sure where it should be reported.
