### ISSUE TITLE
Failed to start server, only sometimes, when changing between two buffers

### ISSUE THREAD

**Issue by shmup** [ternjs/tern_for_vim#184]
Basically I can rely on seeing this error if I change buffers back and forth. It's very easy to replicate.

Using neovim v0.2.0 and the latest tern.

```
Failed to start server:                                                                                                                                                                  
module.js:487                                                                                                                                                                            
    throw err;                                                                                                                                                                           
    ^                                                                                                                                                                                    
Error: Cannot find module '/Users/jmiller/.nvim/bundles/repos/github.com/ternjs/tern_for_vim/node_modules/tern/bin/tern'                                                                 
    at Function.Module._resolveFilename (module.js:485:15)                                                                                                                               
    at Function.Module._load (module.js:437:25)                                                                                                                                          
    at Function.Module.runMain (module.js:605:10)                                                                                                                                        
    at startup (bootstrap_node.js:158:16)                                                                                                                                                
    at bootstrap_node.js:575:3    
```

**Comment by shmup** [comment]
I was too lazy to verify and npm install because I thought my package manager's build setting was working, and evidently not! Heh.
